import{a as y,i as f,S as L}from"./assets/vendor-b0d10f48.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))o(e);new MutationObserver(e=>{for(const r of e)if(r.type==="childList")for(const p of r.addedNodes)p.tagName==="LINK"&&p.rel==="modulepreload"&&o(p)}).observe(document,{childList:!0,subtree:!0});function l(e){const r={};return e.integrity&&(r.integrity=e.integrity),e.referrerPolicy&&(r.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?r.credentials="include":e.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function o(e){if(e.ep)return;e.ep=!0;const r=l(e);fetch(e.href,r)}})();const b="44048092-3090edf6b3c3e0216bf005362",w="https://pixabay.com/api/",h=async(s,t=1,l=15)=>{try{return(await y.get(w,{params:{key:b,q:s,image_type:"photo",per_page:l,page:t}})).data}catch(o){throw f.error({title:"Error",message:"Failed to fetch images. Please try again later."}),o}};function g(s,t){const l=s.map(e=>`
        <li class="gallery-item">
            <a class="gallery-link" href="${e.largeImageURL}">
                <div class="full-image" class="loader">
                    <img class="gallery-image" src="${e.webformatURL}" alt="${e.tags}">
                    <ul class="image-button">
                        <li><p class="info-name">Likes</p><p>${e.likes}</p></li>
                        <li><p class="info-name">Views</p><p>${e.views}</p></li>
                        <li><p class="info-name">Comments</p><p>${e.comments}</p></li>
                        <li><p class="info-name">Downloads</p><p>${e.downloads}</p></li>
                        </ul>
                </div>
            </a>
        </li>
    `).join("");t.insertAdjacentHTML("beforeend",l),new L(".gallery a",{captionsData:"alt",captionDelay:250}).refresh()}function n(s,t){f[t]({message:s,messageColor:"white",position:"topRight",backgroundColor:"red"})}const v=document.querySelector("form"),u=document.querySelector(".gallery"),i=document.querySelector(".loader"),a=document.querySelector(".load-button");let c=1,m=15,d="";a.classList.add("is-hidden");i.classList.add("is-hidden");v.addEventListener("submit",async s=>{if(s.preventDefault(),u.innerHTML="",c=1,d=s.target.elements.search_input.value.trim(),d===""){n("Please enter a search term.","warning");return}i.classList.remove("is-hidden"),a.classList.add("is-hidden");try{const t=await h(d,c,m);if(i.classList.add("is-hidden"),t.total===0){n("Sorry, there are no images matching your search query. Please try again!","error");return}g(t.hits,u),t.totalHits>m?a.classList.remove("is-hidden"):a.classList.add("is-hidden")}catch{i.classList.add("is-hidden"),n("An error occurred while fetching images. Please try again later.","error")}finally{s.target.reset()}});a.addEventListener("click",async()=>{try{c+=1,i.classList.remove("is-hidden"),a.classList.add("is-hidden");const s=await h(d,c,m);if(i.classList.add("is-hidden"),s.hits.length===0){n("No more images to load.","info"),a.classList.add("is-hidden");return}g(s.hits,u),c*m>=s.totalHits?a.classList.add("is-hidden"):a.classList.remove("is-hidden")}catch{i.classList.add("is-hidden"),n("An error occurred while fetching images. Please try again later.","error")}});
//# sourceMappingURL=commonHelpers.js.map
